apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  labels:
    app: viavi-meter-provisioning
data:
  VITE_API_BASE_URL: "https://ldap-api.apps.prod-ocp4.corp.cableone.net"
  VITE_USE_STUB_API: "false"
